name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        if [ -f package.json ] && grep -q "\"test\":" package.json; then
          npm test
        else
          echo "No test script defined. Skipping tests."
        fi
